x-minio-common: &minio-common
  image: quay.io/minio/minio
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  restart: always
  expose:
    - "9000"
    - "9001"
  env_file:
    - "./.env"
  networks:
    - backend
  healthcheck:
    test: ["CMD", "mc", "ready", "local"]
    interval: 5s
    timeout: 5s
    retries: 3

services:
  minio1:
    <<: *minio-common
    container_name: minio1
    hostname: minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2

  minio2:
    <<: *minio-common
    container_name: minio2
    hostname: minio2
    volumes:
      - data2-1:/data1
      - data2-2:/data2

  minio3:
    <<: *minio-common
    container_name: minio3
    hostname: minio3
    volumes:
      - data3-1:/data1
      - data3-2:/data2

  minio4:
    <<: *minio-common
    container_name: minio4
    hostname: minio4
    volumes:
      - data4-1:/data1
      - data4-2:/data2


  nginx:
    image: nginx:1.27.1-alpine
    container_name: nginx
    hostname: nignx
    env_file:
      - ./.env
    restart: always
    volumes:
      # Nginx Conf
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      # Nginx Template
      - ./nginx/templates/http-nginx.conf.template:/etc/nginx/templates/default.conf.template

      # Log Files
      - ./nginx/log/:/var/log/nginx/
      - ./nginx/log/:/var/log/nginx/
    ports:
      - "${NGINX_HTTP_PORT}:${NGINX_HTTP_PORT}"
      - "${MINIO_HTTP_API}:${MINIO_HTTP_API}"
    networks:
      - backend
      - frontend
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4
  
networks:
  frontend:
    name: frontend
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.1.0/24
          gateway: 10.10.1.1

  backend:
    name: backend
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.11.0/24
          gateway: 10.10.11.1

volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2: